name: Vitest

on:
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: CD into root
        run: cd gaming-website
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm run test
